// Generated by CoffeeScript 1.6.3
(function() {
  var Sourced, throws;

  throws = function() {
    throw new Error('No callback defined');
  };

  Sourced = (function() {
    function Sourced(config) {
      if (config == null) {
        config = {};
      }
      this.storage = config.storage;
      if (config.generateUUId != null) {
        this.generateUUId = config.generateUUId;
      }
      this.setDefaults();
    }

    Sourced.prototype.setDefaults = function() {
      if (this.storage == null) {
        return this.storage = new Sourced.MemoryStorage();
      }
    };

    Sourced.prototype.generateUUId = function() {
      return require('uuid').v4();
    };

    Sourced.prototype.createRevision = function(type, uuid, version) {
      if (version == null) {
        version = 0;
      }
      if (uuid == null) {
        uuid = this.generateUUId();
      }
      return new Sourced.Revision({
        resourceType: type,
        resourceId: uuid,
        resourceVersion: version
      });
    };

    Sourced.prototype.storeRevision = function(revision, callback) {
      if (callback == null) {
        callback = throws;
      }
      return this.storage.store(revision, callback);
    };

    return Sourced;

  })();

  Sourced.Revision = require('./Revision');

  Sourced.MemoryStorage = require('./MemoryStorage');

  Sourced.RevisionConflict = require('./RevisionConflict');

  Sourced.RevisionOutOfSequence = require('./RevisionOutOfSequence');

  module.exports = Sourced;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
