// Generated by CoffeeScript 1.6.3
var Sourced;

Sourced = exports;

Sourced.Resource = require("./resource");

Sourced.Revision = require("./revision");

Sourced.MemoryStore = require("./memory-store");

/*
//@ sourceMappingURL=index.map
*/
