// Generated by CoffeeScript 1.6.3
var MemoryStore;

module.exports = MemoryStore = (function() {
  function MemoryStore(props) {
    this.setProperties(props);
    this.setDefaults();
  }

  MemoryStore.prototype.setProperties = function(props) {
    if (props == null) {
      props = {};
    }
    return this.hash = props.hash;
  };

  MemoryStore.prototype.setDefaults = function() {
    if (this.hash == null) {
      return this.hash = {};
    }
  };

  MemoryStore.prototype.store = function(revision, cb) {
    this.hash[revision.id] = revision;
    return cb(null, revision.id);
  };

  MemoryStore.prototype.find = function(id, cb) {
    var revision;
    revision = this.hash[id];
    return cb(null, revision);
  };

  return MemoryStore;

})();

/*
//@ sourceMappingURL=memory-store.map
*/
