// Generated by CoffeeScript 1.6.3
(function() {
  var NotImplemented, SourcedError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SourcedError = require('./SourcedError');

  module.exports = NotImplemented = (function(_super) {
    __extends(NotImplemented, _super);

    function NotImplemented() {
      _ref = NotImplemented.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NotImplemented.prototype.setDefaults = function() {
      if (this.message == null) {
        return this.message = "Not implemented";
      }
    };

    return NotImplemented;

  })(SourcedError);

}).call(this);

/*
//@ sourceMappingURL=NotImplemented.map
*/
