// Generated by CoffeeScript 1.6.3
var Resource, Revision;

Revision = require("./revision");

module.exports = Resource = (function() {
  function Resource(props) {
    this.setProperties(props);
    this.setDefaults();
  }

  Resource.prototype.setProperties = function(props) {
    if (props == null) {
      props = {};
    }
    this.type = props.type;
    this.uuid = props.uuid;
    this.version = props.version;
    return this;
  };

  Resource.prototype.setDefaults = function() {
    if (this.type == null) {
      this.type = this.constructor.name;
    }
    if (this.uuid == null) {
      this.uuid = this.generateUUId();
    }
    if (this.version == null) {
      this.version = 0;
    }
    return this;
  };

  Resource.prototype.generateUUId = function() {
    return require("uuid").v4();
  };

  Resource.prototype.revise = function() {
    return new Revision({
      resourceType: this.type,
      resourceUUId: this.uuid,
      number: this.version + 1
    });
  };

  return Resource;

})();

/*
//@ sourceMappingURL=resource.map
*/
