// Generated by CoffeeScript 1.6.3
(function() {
  var NotImplemented, Resource;

  NotImplemented = require('./NotImplemented');

  module.exports = Resource = (function() {
    function Resource(props) {
      if (props == null) {
        props = {};
      }
      this.uuid = props.uuid;
      Object.defineProperty(this, 'domainName', {
        enumerable: true,
        get: this.getDomainName
      });
      Object.defineProperty(this, 'type', {
        enumerable: true,
        get: this.getType
      });
      this.setDefaults();
    }

    Resource.prototype.setDefaults = function() {
      if (this.uuid == null) {
        return this.uuid = this.generateUUId();
      }
    };

    Resource.prototype.generateUUId = function() {
      return require('uuid').v4();
    };

    Resource.prototype.getDomainName = function() {
      throw new NotImplemented;
    };

    Resource.prototype.getType = function() {
      throw new NotImplemented;
    };

    return Resource;

  })();

}).call(this);

/*
//@ sourceMappingURL=Resource.map
*/
