// Generated by CoffeeScript 1.6.3
(function() {
  var RevisionOutOfSequence;

  module.exports = RevisionOutOfSequence = (function() {
    function RevisionOutOfSequence() {
      Error.call(this);
      Error.captureStackTrace(this, this.constructor);
      this.name = this.constructor.name;
    }

    return RevisionOutOfSequence;

  })();

}).call(this);

/*
//@ sourceMappingURL=RevisionOutOfSequence.map
*/
