// Generated by CoffeeScript 1.6.3
(function() {
  var RevisionConflict,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = RevisionConflict = (function(_super) {
    __extends(RevisionConflict, _super);

    function RevisionConflict() {
      Error.call(this);
      Error.captureStackTrace(this, this.constructor);
      this.name = 'RevisionConflict';
    }

    return RevisionConflict;

  })(Error);

}).call(this);

/*
//@ sourceMappingURL=RevisionConflict.map
*/
