// Generated by CoffeeScript 1.6.3
(function() {
  var SourcedError, TypeUnknown,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SourcedError = require('./SourcedError');

  TypeUnknown = (function(_super) {
    __extends(TypeUnknown, _super);

    function TypeUnknown(props) {
      if (props == null) {
        props = {};
      }
      this.typeName = props.typeName;
      TypeUnknown.__super__.constructor.apply(this, arguments);
    }

    TypeUnknown.prototype.setDefaults = function() {
      this.message = "Unknown type: '" + this.typeName + "'";
      return TypeUnknown.__super__.setDefaults.apply(this, arguments);
    };

    return TypeUnknown;

  })(SourcedError);

  module.exports = TypeUnknown;

}).call(this);

/*
//@ sourceMappingURL=TypeUnknown.map
*/
